name: collapse_thresholds
channels:
  - conda-forge
dependencies:
# Tested with Python 3.13.9
  - python=3.13
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - pyyaml
  - jupyter
  - pip
  - pip:
      - tqdm
